15 forms
MaksKulykov/Forms pull request #1
Opened 2017-07-24 13:25 UTC by MaksKulykov

2017-07-24 19:43 UTC, fullstackdb requested changes
незначительные изминения запрошены

2017-07-24 19:43 UTC, fullstackdb commented on src/app/login/login.component.html
> +        Не верный пароль. Пароль должен включать не менее 10 символов, как минимум 1 букву в верхнем регистре и 1 цифру.
Совет.

Попробуйте использовать i18n для работы с сообщениями
[ссылка](https://angular.io/guide/i18n)

2017-07-24 19:43 UTC, fullstackdb commented on src/app/end/end.component.ts
> +  msg: any = 'Ваша операция прошла успешно!';
Совет.

Попробуйте использовать i18n для работы с сообщениями
[ссылка](https://angular.io/guide/i18n)

2017-07-24 19:43 UTC, fullstackdb commented on src/app/login/login.component.ts
> +    this.login = {userEmail: '', userPassword: ''};
совет 

задайте дефолтные значения для модели и создайте новый екземпляр при помощи ключевого слова  new
```
this.login = new LoginModel();
```

2017-07-24 19:43 UTC, fullstackdb commented on src/app/pay-phone/pay-phone.component.ts
> +  pay: Pay = {phone: '', price: '', userEmail: '', cardNumber: '', month: '', year: '', cvv: ''};
совет 

задайте дефолтные значения для модели и создайте новый екземпляр при помощи ключевого слова  new
```
this.login = new PayPhone();
```

2017-07-24 19:43 UTC, fullstackdb commented on src/app/pay-phone/pay-phone.component.ts
> +  constructor() {}
удалите пустой конструктор

2017-07-25 09:28 UTC, MaksKulykov commented on src/app/login/login.component.ts
> +    this.login = {userEmail: '', userPassword: ''};
@fullstackdb done

2017-07-25 09:28 UTC, MaksKulykov commented on src/app/pay-phone/pay-phone.component.ts
> +  pay: Pay = {phone: '', price: '', userEmail: '', cardNumber: '', month: '', year: '', cvv: ''};
@fullstackdb done

2017-07-25 09:29 UTC, MaksKulykov commented on src/app/pay-phone/pay-phone.component.ts
> +  constructor() {}
@fullstackdb done

2017-08-03 10:52 UTC, MaksKulykov commented on src/app/login/login.component.html
> +        Не верный пароль. Пароль должен включать не менее 10 символов, как минимум 1 букву в верхнем регистре и 1 цифру.
@fullstackdb done

2017-08-03 10:53 UTC, MaksKulykov commented on src/app/end/end.component.ts
> +  msg: any = 'Ваша операция прошла успешно!';
@fullstackdb done

2017-08-11 15:50 UTC, fullstackdb approved these changes

2017-08-11 16:21 UTC, merged